name: "Blog·Tanky Woo"
description: "Tanky Woo's Blog, focus on Python, Linux, Gentoo, Mac OS, Vim, Open Source and so on."
url: "http://blog.tankywoo.com"
markdown: redcarpet
highlighter: pygments
exclude: ["fabfile.py*", "*.bak"]
permalink: /:year/:month/:day/:title.html
